name: GitHub Actions Workflow
on:
  push: 
  workflow_dispatch: 

jobs:
  initial:
    name: "First job"
    runs-on: ubuntu-latest
    outputs: 
      testing-value: ${{ steps.firstAction.outputs.testing-value }}
    steps:
      - name: "First action"
        id: firstAction
        run: echo "Testing" >> "$GITHUB_OUTPUT"
        
  second:
    name: "Second job"
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - name: "Second action"
        run: |
        echo "Got from initial: ${{ needs.initial.outputs.testing-value }}"
