name: GitHub Actions Workflow
on:
  push: 
  workflow_dispatch: 

jobs:
  initial:
    name: "Initial testing"
    runs-on: ubuntu-latest
    steps:
      - name: "First action"
        run: echo "Testing"
